version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=safe_village
    ports:
      - "5432:5432"
    volumes:
      - C:\volumes\SafeVillage:/docker-entrypoint-initdb.d
